export const OPEN_EYE_PROBABILITY_THRESHOLD = 0.6;
export const BLINK_COUNT_THRESHOLD_LOW = 0;
export const BLINK_COUNT_THRESHOLD_HIGH = 30;
export const EYECLOSURE_TIME_THRESHOLD = 2000;
export const PITCH_DOWN_ANGLE_THRESHOLD = -5;
export const PITCH_UP_ANGLE_THRESHOLD = 15;
export const LOOKDOWN_TIME_THRESHOLD = 5000;
