export const BLINK_COUNT_THRESHOLD_LOW = 8;
export const BLINK_COUNT_THRESHOLD_HIGH = 20;
export const OPEN_EYE_PROBABILITY_THRESHOLD = 0.7;
export const EYECLOSURE_TIME_THRESHOLD = 1500;
export const PITCH_DOWN_ANGLE_THRESHOLD = -5;
export const PITCH_UP_ANGLE_THRESHOLD = 15;
export const LOOKDOWN_TIME_THRESHOLD = 5000;
